name: camera_app
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.5+4
  google_mlkit_pose_detection: ^0.9.0
  google_mlkit_face_detection: ^0.8.0
  google_mlkit_selfie_segmentation: ^0.5.0
  get_it: ^7.6.4
  injectable: ^2.3.2
  rxdart: ^0.27.7
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.4.1
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

